ska-sa/katsdpcontim

- katacomb/katacomb/aips_export.py
1. The run number was always "0". A stored dict wasn't being copied in
memory causing later updates to the original to change the preserved copy.
2. Correctly report the integration time per target only on "tracks"
> Fix two bugs while writing the metadata.json

- katacomb/katacomb/conf/mfimage_MKAT.yaml
- katacomb/katacomb/continuum_pipeline.py
Add a continuum_pipeline method to determine a default maximum run-time for MFImage.
The default is the maximum of either 2 hours or the observation length + 50%. This can be overridden by setting the value of MFImage parameter maxRealtime at execution either at the command-line or in the configuration yaml.
Also remove the old (6 hour) default from the configuration file.
> Maximum imaging run-time

- katacomb/katacomb/conf/mfimage_MKAT.yaml
- katacomb/katacomb/conf/uvblavg_MKAT.yaml
- katacomb/katacomb/continuum_pipeline.py
- katacomb/scripts/continuum_pipeline.py
Infer the refant from the cal_refant and the channel averaging
so we should always average to 1K channels for continuum.
Delete relevant parameters from the configuration defaults.
Also move the maxRuntime code into the infer_defaults function.
Also Fix broken baseline averaging parameter. (This should be
the same as what we use as the self-calibration interval.)
> Add default parameters inferred from katdal object.

- katacomb/katacomb/continuum_pipeline.py
- katacomb/katacomb/img_facade.py
- katacomb/katacomb/uv_facade.py
Add 2 improvements to the images generated.
1. The image is computed using a weighted average of the coarse frequency planes rather then fitting a 1st order spectrum per pixel- this removes discontinuities in the continuum images. Retain the spectral index image formed from the pixel fitting in the second plane.
2. Attach the raw SN (self calibration solution) tables and CC (clean component model) table to the output FITS image.
> Image export updates

- katacomb/katacomb/continuum_pipeline.py
This stops the resulting image having a blank continuum plane.
> Re-instantiate tmp_img after averaging the coarse frequency planes

- obit.patch
A small patch to fix the a smashing error in Obit with the updated ubuntu in the base docker image and get the contim containers building again.
I'll send this fix to Bill so it can be fixed inside the Obit codebase properly but in the interim this patch will get things working again.
(Don't merge until it passes the tests)
> Patch Obit r598

- katacomb/katacomb/katdal_adapter.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
Also- ensure that the UV header 'SOURCE' keyword has 16 characters.
The AIPS file names of imaged targets are derived from their SOURCE
keyword in the input AIPS UV header. Source names were being truncated
to 16 characters, which is the required length of the SOURCE keyword
in an AIPS UV header, via the `normalise_target_name` function. AIPS
file names have a maximum length of 12 characters. While some Obit
tasks can handle this descrepancy (i.e. MFImage will truncate filenames
derived from the SOURCE parameter to 12 characters), others cannot
(i.e. TabCopy) and require that filenames (derived from outName and
inName parameters) are a maximum of 12 characters.
The workaround is to require that all SOURCE header keywords (derived
from katpoint target names) are truncated to 12 characters, …
> Truncate AIPS path names to 12 characters

- Jenkinsfile
- katacomb/requirements.txt
- Change dependency on katsdpdockerbase from python2 back to master
- Remove some packages that are no longer needed on Python 3 and
potentially no longer pinned by katsdpdockerbase.
> Fix the build

- katacomb/requirements.txt
This should be merged together with ska-sa/katsdpdockerbase#46. It may
currently fail to build until that branch is merged.
> Update requirements to match katsdpdockerbase update

- katacomb/katacomb/__init__.py
- katacomb/katacomb/aips_export.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
- katacomb/katacomb/util/image_util.py
- katacomb/requirements.txt
- katacomb/scripts/continuum_pipeline.py
Use the zscale algorithm from katsdpsigproc now that it has moved there. The rest is largely a cut-and-paste job from `render.py` in katsdpimager. The commit messages describe the changes I needed to make for continuum images.
@bmerry, as we discussed, this (or a variant) could go somewhere else where both katsdpimager and katsdpcontim can import it. I suspect zscale could also leave katsdpsigproc and join it as well. As such this PR is really just an indication of how things will work for the continuum case so we can identify whether or not the implementations have enough in common to move things somewhere else. I'll put a 'do not merge' on this while we work that out.
> Update PNG rendering

- katacomb/katacomb/conf/mfimage.yaml
- katacomb/katacomb/conf/uvblavg.yaml
- katacomb/scripts/continuum_image.py
Get the cal reference antenna if it is available and switch off the max Wall time in offline mode.
Any can be overridden by a user supplied .yaml or command line arguments.
> Offline imager updates

- katacomb/katacomb/aips_export.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
Add BMAJ, BMIN, BPA keywords to FITS headers so that external software knows about the CLEAN beam.
Also change BUNIT to 'Jy/beam' (FITS v4.0 standard) from 'JY/BEAM' (AIPS standard). This stops astropy from complaining.
> Update FITS headers

- katacomb/katacomb/conf/mfimage.yaml
- katacomb/katacomb/conf/mfimage_MKAT.yaml
- katacomb/katacomb/conf/uvblavg_MKAT.yaml
- katacomb/katacomb/continuum_pipeline.py
Increase the diameter of the outlier facets put on SUMSS source positions to 200 pixels. This ensures that any complex structure missed in the SUMSS catalogue is covered by the image grid and can be deconvolved more accurately.
Also increase the maximum interval for baseline dependent averaging to 1 minute. From testing, this makes a typical visibility dataset about 15% smaller and the imager run about 10% faster. This requires that the self-calibration interval be increased to 1 minute as well. I've tested this change on a number of datasets and the increase has no discernible effect on the resulting images.
Finally, make MFImage a bit more chatty by increasing its log level from 1 to 2 (out of 5).
> Expand outlier fields

- katacomb/scripts/continuum_image.py
The offline imager currently applies l2 gains by default. This creates some confusion when running it so add a log message to indicate the applycal option being passed to katdal. Also change the default to l1 since the more common use case of the offline imager is to redo the online imaging rather than expand it.
> Change offline default applycal to 'l1'

- katacomb/katacomb/katdal_adapter.py
It was out by a couple of m/s for some reason.
Don't mess with the fine structure constant!
> Correct the hard-coded value of lightspeed.

- katacomb/katacomb/aips_export.py
- katacomb/katacomb/continuum_pipeline.py
- katacomb/katacomb/img_facade.py
- katacomb/katacomb/katdal_adapter.py
- katacomb/katacomb/obit_context.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
- katacomb/katacomb/util/__init__.py
- katacomb/scripts/continuum_image.py
- katacomb/scripts/continuum_pipeline.py
In the event that the imager times out before the self-calibration cycles are complete, make sure that calibration solutions that are available are still exported.
Details are in the commit messages.
> Improve solution export

- katacomb/katacomb/aips_export.py
- katacomb/katacomb/continuum_pipeline.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
Have the `execute` method of both the online and offline `:class:Pipeline` instances return the `metadata` dictionary that was saved by `export_images`. This dictionary contains information that can be subsequently used by modules (e.g. QA reporting) that need pertinent information about the pipeline run results (e.g. FITS image filenames).
> Return products

- katacomb/requirements.txt
Previously Aegean and mpld3 were installed from the master branch
of their git repositories which risks changes to these repos
accidentally breaking the QA report code. It is preferable to install
them from the PyPI released versions to ensure stability.
> Use PyPI release versions in requirements

- katacomb/katacomb/aips_export.py
- katacomb/katacomb/katdal_adapter.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
`BANDCODE` is the keyword used in AIPS Memo 117 so I thought I would stick to that. The other change makes sure the `INSTRUME` keyword in the fits header contains the product name (as per spectral images).
> Update FITS headers to include band and product info.

- katacomb/katacomb/qa_report.py
- katacomb/requirements.txt
The recent merge of https://github.com/ska-sa/katsdpimageutils/pull/10 to master broke katsdpcontim due to adding https://github.com/ska-sa/katbeam as a requirement, and due to a minor change in the interface to the `beam_pattern` function.
This updates things so that it works again.
> Update for changes to katsdpimageutils

- katacomb/katacomb/qa_report.py
I accidently made it an str(float) and this is causing the metadata validator to fail. Products with this updated RMSNoise therefore won't appear in the archive
> Make 'RMSNoise' in metadata a list

- Dockerfile
SPR1-1324 notes an issue with the continuum images not being produced.
This is because the docker base gpu image had been updated to use CUDA 11.3
while the samples in the docker image for katsdpcontim are still from CUDA 10.0.
This updates CUDA to 11.3.
> Update to CUDA 11.3 to be in line with the base GPU docker image

- Dockerfile
Reverts ska-sa/katsdpcontim#41
See SPR1-1324. CUDA 11.3 is for now too new for our site and build servers and katsdpdockerbase in now reverted.
> Revert "Update to CUDA 11.3 to be in line with the base GPU docker image"

- katacomb/katacomb/aips_export.py
- katacomb/katacomb/qa_report.py
The contrast of the raw and primary beam corrected PNG images output by the pipeline was set to the default value of 0.02 from the zscale algorithm in katsdpimageutils. This results in `vmin` and `vmax` values that are too far from the mean, and the resulting PNGs are too dark to see many features.
This updates the contrast to 0.5 for the raw MFImage output and to 0.3 for the PB corrected image. The mean and rms images are fine with the default value and I've left them unchanged.
The modified contrast makes it easier to see features in the images that make them more useful for QA appraisal.
Some examples of the effect of these changes are shown in JIRA ticket SPR1-1296
> Improve contrast of PNG images.

- katacomb/katacomb/conf/mfimage_MKAT_S.yaml
This creates 8 sub-bands during imaging rather than the 6 with maxFBW=5%
and stops an as yet unfixed MFImage bug causing deconvoluton in the second
sub-band to diverge. The change has minimal cost to MFImage runtime.
> Decrease maxFBW in MFImage to 4.5% for online S-band.

- katacomb/katacomb/conf/mfimage_MKAT_S.yaml
This ensures at least 8 imaging sub-bands for any of S0 to S4 in S-band.
> Change maxFBW to 0.038 for online S-band

- katacomb/katacomb/continuum_pipeline.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
- katacomb/scripts/continuum_pipeline.py
This is to address SPR1-1830, currently if all the visibilities are
flagged the online pipeline throws an exception. This PR checks that
there a non-zero number of unflagged visibilities in the merged dataset
before proceeding to imaging. If no unflagged visibilities exist the
pipeline will log an error and terminate without any attempt to image an
empty dataset.
> Exit gracefully if 100% of the data is flagged

- Dockerfile
Very small change. The Dockerfile VOLUME command needs double literals after docker-ce upgrade on jenkins build agents.
> Update single literals to double literals

- katacomb/katacomb/conf/uvblavg_MKAT_narrow_L.yaml
- katacomb/katacomb/conf/uvblavg_narrow_L.yaml
This ensures that the the data is averaged to 256 channels before going into the imager by default in both offline and online mode.
> Update narrowband averaging parameters.

- katacomb/katacomb/__init__.py
- katacomb/katacomb/tests/test_qa.py
- katacomb/scripts/continuum_pipeline.py
This fixes an issue where the scripts cannot be run from outside the katsdpcontim docker container due to them requiring the Meerkat-continuum-validation library to be placed in `/home/kat/valid` on the local filesystem (a location that isn't generally writeable by any given user on any given machine).
The fix is simply to move the import of the continuum validation machinery out of the module and into the online (`continuum_pipeluine.py`) script. This allows the offline scripts to be run without trying to import the QA code, which they don't actually use anyway. Now the offline scripts can be run from outside or inside the docker container, but the online script can only be run from inside the docker container (unless the appropriate software is copied to `/home/kat/valid` on the host …
> Move the QA report and PB import from the module to the script level.

- katacomb/katacomb/aips_export.py
- katacomb/katacomb/conf/parameters/MKAT_narrow_L.yaml
- katacomb/katacomb/conf/parameters/narrow_L.yaml
- katacomb/katacomb/util/__init__.py
Change narrow band imaging to use 2 IFs for both 107M and 54M and use `maxFBW=0.02` for the narrow band coarse frequency planes. This will provide 4 planes in 107M and 2 in 54M. The CLEAN components in the two planes in 54M will be overfitted by the default polynomial order 2, so in this case fall back to a polynomial of order (Nplanes - 1).
> Two frequency planes for narrowband

- Dockerfile
As of CUDA 11.6 the samples are no longer available in the toolkit so retrieve them from NVIDIA's github repo instead. The headers are placed in /usr/local/cuda/samples/inc which is where the GPU Obit build modified by 'obit.patch' looks for them.
This should make things easier to maintain for newer versions of CUDA in future.
> Get CUDA samples from NVIDA's github repo.

- katacomb/katacomb/aips_export.py
- katacomb/katacomb/aips_path.py
- katacomb/katacomb/aips_table.py
- katacomb/katacomb/continuum_pipeline.py
- katacomb/katacomb/img_facade.py
- katacomb/katacomb/katdal_adapter.py
- katacomb/katacomb/mock_dataset.py
- katacomb/katacomb/qa_report.py
- katacomb/katacomb/tests/test_aips_facades.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
- katacomb/katacomb/tests/test_qa.py
- katacomb/katacomb/tests/test_uv_export.py
- katacomb/katacomb/util/__init__.py
- katacomb/requirements.txt
- katacomb/scripts/cfg_aips_disks.py
Fix some warnings in Python 3.8 and dependencies that are broken in Python 3.10.
The first commit bumps some local dependent packages in `requirements.txt` - Other unpinned packages (like `numba`, `numpy` & `dask`) are pinned in dockerbase and someone will have to work out suitable versions of these separately.
The remaining commits can be followed one at a time, and fix things that are spitting warnings about being deprecated or are broken in Python>=3.8.
> Updates to ensure compatibility with Python 3.10

- Dockerfile
- katacomb/katacomb/tests/test_aips_facades.py
- katacomb/katacomb/tests/test_continuum_pipeline.py
- katacomb/katacomb/uv_facade.py
The background to this PR is that katsdpcontim hasn't built on CI/Jenkins for some time. This is due to Github sunsetting svn support https://github.blog/news-insights/product-news/sunsetting-subversion-support/. I've changed the dockerfile so that Obit is built from source at its github URL, rather than a pinned svn-over-git version. This has had several side-effects, the first being that Obit version has been updated to 668.
As a consequence of this, katsdpcontim no longer behaves as it did previously. I narrowed it down to the way sequential writes are handled in UVFacade. There was an interesting-in-its-logic switch on a parameter passed to the ::Write method, that would affect the previous buffer pointer in Obit. I assume this had been done to work around behaviour of Obit at that …
> SPR1-3213 make UVFacade sequential write work again.
